[[annotations]]
id = 1
chapter = "Epigram"
page = 11
quote = "This is the truth. You will know because it hurts."
notes = "<i>We open with an epigram. I like epigrams! This is doing a lot of work. It warns readers who aren’t in the mood for a dark read to flee. It claims that truth is painful, and that pain can establish truth. Readers should be suspicious: is something painful inherently more valuable and truthful? What about love and joy? This epigram is an act of deceit, establishing one of Baru’s character flaws.<br/><br/>A note on structure. Before I set a single word down in Baru Cormorant, I blocked out three acts, each of ten chapters, each of about four 1000 word scenes (subject to change). This let me know when I had to key up tension, and when to key down. I think a lot about arcs and the cycle of tension, and I hope that makes the book compelling. In each structural unit I try to map out an arc.</i> (source: <a href='https://www.sethdickinson.com/2015/10/01/the-traitor-baru-cormorant-read-along-chapter-1/'>The Traitor Baru Cormorant read-along: Chapter 1</a>)"
shortname = "you will know because it hurts"
tags = ["truth", "pain", "lying", "author commentary"]

[[annotations]]
id = 19
chapter = "Accountant 1"
page = 15
quote = "Baru was still too young to smell the empire wind."
notes = "A double-meaning here. Baru can't smell the Trade Wind, which circles the Ashen Sea (and enables Falcrest's naval domination, hence the name 'empire wind'). But she has also previously been unaware of the arrival of Falcrest's actions on Taranoke; their first appearance in the narrative is not their first time exerting influence on Taranoki culture.<br/><br/>As noted later, Baru is seven in this scene."
shortname = "still too young"
tags = ["trade wind", "colonization", "unreliable narration"]

[[annotations]]
id = 20
chapter = "Accountant 1"
page = 15
quote = "The Masquerade sent its favorite soldiers to conquer Taranoke…"
notes = "<i>The first page of the book focuses on Baru, the Masquerade, then Baru again. We are with her, counting the ships. But we are also arriving with the Masquerade, seeing her do things that will make her valuable to us. We are colonizing Baru, shaping her into a character who tells us a story, and she manipulates us by focusing on things we’ll find interesting.</i> (source: <a href='https://www.sethdickinson.com/2015/10/01/the-traitor-baru-cormorant-read-along-chapter-1/'>The Traitor Baru Cormorant read-along: Chapter 1</a>)"
shortname = "the Masquerade's favorite soldiers"
tags = ["colonization", "unreliable narration", "author commentary"]

[[annotations]]
id = 21
chapter = "Accountant 1"
page = 15
quote = "...watching firebearer frigates heel in the aurora light…"
notes = "<i>I’m torn about this flash-forward. I wanted to tell readers, hey, don’t worry, this book will have action! But it’s cowardly to jump forward and then back, just for excitement. And the sentence might be overloaded. Firebearer or aurora, perhaps not both?</i> (source: <a href='https://www.sethdickinson.com/2015/10/01/the-traitor-baru-cormorant-read-along-chapter-1/'>The Traitor Baru Cormorant read-along: Chapter 1</a>)"
shortname = "firebearer frigates"
tags = ["navy", "author commentary"]

[[annotations]]
id = 22
chapter = "Accountant 1"
page = 15
quote = "...the kelp for ash, the ash meant for glass..."
notes = "<i>The Ashen Sea is actually named for the useful ash you can get from burning its plentiful kelp.</i> (source: <a href='https://www.sethdickinson.com/2015/10/01/the-traitor-baru-cormorant-read-along-chapter-1/'>The Traitor Baru Cormorant read-along: Chapter 1</a>)"
shortname = "kelp for ash"
tags = ["Ashen Sea", "author commentary"]

[[annotations]]
id = 23
chapter = "Accountant 1"
page = 15
quote = "...Halae’s Reef..."
notes = "<i>Taranoke is meant to be its own creation, not an analog for any Earthly place. But I can see why people start with Hawaii as a basis, with names like this. Another major landmark near Taranoke is the Navel, a creepy blue hole.</i> (source: <a href='https://www.sethdickinson.com/2015/10/01/the-traitor-baru-cormorant-read-along-chapter-1/'>The Traitor Baru Cormorant read-along: Chapter 1</a>)"
shortname = "Halae's Reef"
tags = ["Taranoke", "author commentary"]

[[annotations]]
id = 24
chapter = "Accountant 1"
page = 15
quote = "'Look, Das,' Baru said."
notes = "<i>Das</i>, here, being a translation of a Urunoki plural for 'father'. Baru is addressing both Solit and Salm.<br/><br/>Given the cultural acceptance of polyamory and communal child-rearing, these would be a natural part of Urunoki, unlike the awkward-sounding 'fathers' or 'Dads' in English. 'Das' is a good translation."
shortname = "'Das'"
tags = ["language"]

[[annotations]]
id = 25
chapter = "Accountant 1"
page = 15
quote = "...callused hand pressed against his husband’s bare strength..."
notes = "<i>It was a struggle to characterize these two in very little space. I wrestled with this sentence because I didn’t want to code Solit as effeminate and Salm as masculine. I think it turned out okay.</i> (source: <a href='https://www.sethdickinson.com/2015/10/01/the-traitor-baru-cormorant-read-along-chapter-1/'>The Traitor Baru Cormorant read-along: Chapter 1</a>)"
shortname = "callused hand"
tags = ["gender", "author commentary"]

[[annotations]]
id = 26
chapter = "Accountant 1"
page = 16
quote = "...loved her mother and her father dearly, but she loved to know things just a small measure more, and she had recently discovered cunning."
notes = "<i>Even at age seven, Baru’s unable to disentangle her emotional life from her desire for knowledge, which becomes her desire for power. Poor Baru! Note also that Baru is already an active agent, manipulating the plot. One of the design tenets of Baru’s character is that she is highly agentic.</i> (source: <a href='https://www.sethdickinson.com/2015/10/01/the-traitor-baru-cormorant-read-along-chapter-1/'>The Traitor Baru Cormorant read-along: Chapter 1</a>)"
shortname = "a small measure more"
tags = ["knowledge", "author commentary"]

[[annotations]]
id = 27
chapter = "Accountant 1"
page = 16
quote = "She opened her mother's hand-copied dictionary..."
notes = "Taranoke has written language, and a good understanding of glassworking and optics (given their production of telescopes); but they have not, it appears, developed a printing press."
shortname = "hand-copied dictionary"
tags = ["language", "author commentary"]
related = [31]

[[annotations]]
id = 28
chapter = "Accountant 1"
page = 16
quote = "...the Urunoki alphabet..."
notes = "<i>A descendant of Maia Urun, just as the people of Taranoke are descendants of the Tu Maia. They settled Taranoke while trying to find Oriati Mbo, ahead of the first wave of militant Maia expansionism. Were there prior inhabitants on Taranoke, cruelly displaced? I don’t know!</i> (source: <a href='https://www.sethdickinson.com/2015/10/01/the-traitor-baru-cormorant-read-along-chapter-1/'>The Traitor Baru Cormorant read-along: Chapter 1</a>)"
shortname = "the Urunoki alphabet"
tags = ["language", "Tu Maia", "author commentary"]

[[annotations]]
id = 29
chapter = "Accountant 1"
page = 16
quote = "...her mother’s dictionary..."
notes = "<i>One of the few pieces of characterization Pinion gets. Although she’s a huntress, she also loves books and knowledge. I have a bunch of scenes with her interacting with Solit, but they didn’t make this book. Family configurations on Taranoke are flexible, but in this case all three of the spouses are in love.</i> (source: <a href='https://www.sethdickinson.com/2015/10/01/the-traitor-baru-cormorant-read-along-chapter-1/'>The Traitor Baru Cormorant read-along: Chapter 1</a>)"
shortname = "worrying about the treaty again"
tags = ["language", "Pinion", "author commentary"]

[[annotations]]
id = 30
chapter = "Accountant 1"
page = 16
quote = "...<i>A Primer in Aphalone</i>..."
notes = "<i>The Falcrest trade language. It’s rendered in the text as a fairly Anglic language, because I want to make it the most familiar-seeming to the reader, so as to seduce and implicate the reader in Falcrest’s perspective. Mwa ha ha!</i> (source: <a href='https://www.sethdickinson.com/2015/10/01/the-traitor-baru-cormorant-read-along-chapter-1/'>The Traitor Baru Cormorant read-along: Chapter 1</a>)"
shortname = "A Primer in Aphalone"
tags = ["language", "author commentary"]

[[annotations]]
id = 31
chapter = "Accountant 1"
page = 16
quote = "There was a copy number in the bottom corner, almost higher than she could count."
notes = "The Falcresti have discovered the printing press, and are using it to spread their cultural influence.<br/><br/>A precocious seven year old can count past 100. If the copy number is almost higher than Baru can count, then there are probably hundreds of these primers on Taranoke already."
shortname = "a copy number"
tags = ["language", "colonization"]
related = [27]